#Juan Camilo Serrano Correa
##Taller 1

In [1]:
import numpy as np

1. Dadas las 2 matrices numpy dimensionales similares, ¿cómo obtener una salida de
matriz numpy en la que cada elemento es una suma de elementos de las 2 matrices
numpy?

In [6]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[20,21,22],[23,24,25]])
c1 = a+b
print(c1)

[[21 23 25]
 [27 29 31]]


2. Dada una matriz numpy (matriz), ¿cómo obtener una salida de matriz numpy que
sea igual a la matriz original multiplicada por un escalar (2)?

In [8]:
c2= b*2
print(c2)

[[40 42 44]
 [46 48 50]]


3. Cree una matriz de identidad de dimensión 4 por 4

In [10]:
c3 =np.identity(4)
print(c3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4. Convierta una matriz 1-D en una matriz 3-D

In [17]:
R = np.arange(1,28)
print(R)
c4 = R.reshape(3,3,3)
print(c4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


5. Crear una matriz de 10x10 con unos (1) en los bordes y ceros (0) en el interior (con
rangos de índices)

In [61]:
ceros = np.zeros((10,10))
print(ceros)

ceros[:1,:]=1
print(ceros)
ceros[-1:,:]=1
print(ceros)
ceros[:,:1]=1
print(ceros)
ceros[:,-1:]=1
print(ceros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1.

6. Generación de secuencias personalizadas: Genere una secuencia de números en
forma de matriz numpy de 0 a 100 con espacios de 2 números, por ejemplo: 0, 2, 4

In [32]:
c6 = np.arange(0,101,2)
print(c6)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


7. Obtener las posiciones (índices) donde coinciden los elementos de 2 matrices
numpy: De 2 matrices numpy, extraiga los índices en los que coinciden los elementos
de las 2 matrices

In [69]:
a7= np.array([1,2,3,4,5])
b7= np.array([1,3,5,4,5])

c7 = np.where((a7 == b7))
print(c7)

(array([0, 3, 4]),)


8. Seno de un ángulo (en radianes): Calcule el seno de una matriz de ángulos (en
radianes) usando NumPy

In [51]:
a8= np.array([3.14, 3.14/2, 6.28])
c8 = np.sin(a8)
print(c8)

[ 0.00159265  0.99999968 -0.0031853 ]


9. Extraiga la especie de la columna de texto del iris 1D.

In [68]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
#print(iris_1d[:5])


species = np.array([row[4] for row in iris_1d])
species[:5]

<ipython-input-68-80b62590c9b3>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

10. Convierta el iris 1D en una matriz 2D iris_2d omitiendo el campo de texto de la
especie.

In [71]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [72]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype=float, usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])